version: "3.4"
services:
  server:
    hostname: server
    build:
      context: .
      target: server
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - .:/srv
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./oar3/etc/oar/admission_rules.d:/etc/oar/admission_rules.d
    networks:
      - oar

  frontend:
    hostname: frontend
    privileged: true
    ports:
      - 8000:80
      - 8001:8001 # <---- HERE
      - 6668:6668
    build:
      context: .
      target: frontend
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - .:/srv
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./oar3/etc/oar/admission_rules.d:/etc/oar/admission_rules.d
    networks:
      - oar

  node:
    privileged: true
    build:
      context: .
      target: node
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - .:/srv
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./oar3/etc/oar/admission_rules.d:/etc/oar/admission_rules.d
    networks:
      - oar

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-oar@oar.test}
      PGADMIN_DEFAULT_USER: ${PGADMIN_DEFAULT_USER:-oar}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-oar}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - oar

networks:
  oar:
    driver: bridge

volumes:
    pgadmin:

