version: '3.7'

x-default-service: &defaults
  restart: unless-stopped
  environment:
    POSTGRES_HOST: postgres_db
    POSTGRES_PASSWORD: oar
    POSTGRES_DB: oar
    POSTGRES_USER: oar
    POSTGRES_USER_RO: oar_ro
    DB_TYPE: postgresql

services:

  app:
    <<: *defaults
    build:
      context: $ROOT_PROJECT
      dockerfile: $ROOT_PROJECT/scripts/ci/docker/Dockerfile
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.7}
    depends_on:
      - postgres_db
    volumes:
      - $ROOT_PROJECT:/app

  postgres_db:
    <<: *defaults
    volumes:
      - $ROOT_PROJECT/scripts/ci/docker/postgresql/01-create-oar-ro.sh:/docker-entrypoint-initdb.d/01-create-oar-ro.sh
    image: ${POSTGRES_IMAGE:-postgres:9.5}
